services:
  dev:
    build: .
    container_name: detectron2
    tty: true
    shm_size: 16G
    environment:
      - TERM=xterm-256color
    volumes:
      - .:/workspace
      - ~/.ssh:/root/.ssh
    working_dir: /workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    network_mode: host