channels:
  - conda-forge
  - pytorch
  - nvidia
dependencies:
  - pytorch
  - torchvision
  # - pytorch-cuda=12.4
  - detectron2
  # - git+https://github.com/facebookresearch/detectron2.git
  - jupyterlab
  - opencv
  - scikit-image
  - filterpy
  - numpy
  - scipy